AllCops:
  Include:
    - Gemfile
    - lib/**/*
  Excludes:
    - spec/**/*

Encoding:
  Enabled: false

LineLength:
  Max: 100

# Enforce old-school for ruby 1.8.7 (el6).
#
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: hash_rockets
